name: Deploy via ftp - SOMENTE DEPLOY

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # NENHUMA INSTALAÇÃO. NENHUM BUILD.

    # 1. Deploy via FTP
    - name: FTP Deploy Locaweb (APENAS TRANSFERÊNCIA)
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }}         
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        # Assumimos que 'dist' está no seu repositório Git!
         remoteDir: "public_html"
