name: Deploy via ftp # Nome do seu workflow

on:
  push:
    branches: [ "main" ] # Dispara na ação 'push' para a branch 'main'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # 1. Configurar Node.js (necessário para o próximo passo)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use a versão do seu projeto

    # 2. Instalar Dependências (npm i) NO RUNNER DO GITHUB
    # Usamos o flag --production para não instalar 'devDependencies', economizando espaço e tempo.
    - name: Install Dependencies (npm i --production)
      run: npm install --production
      
    # 3. Deploy via FTP
    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }}         
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        # Mude localDir para o diretório raiz do seu projeto 
        # (onde estão o código e a pasta node_modules que acabamos de instalar)
        # Se você já faz o build para 'dist', mantenha 'dist', 
        # mas se for um backend, o '.' é o mais provável.
        remoteDir: "/home/pousadamanicaca/public_html"
