name: Deploy via ftp # Nome do seu workflow

on:
  push:
    branches: [ "main" ] # Dispara na ação 'push' para a branch 'main'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # 1. Configurar Node.js (necessário para o próximo passo)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc' # <--- O setup-node lerá a versão do arquivo

    # 2. Instalar Dependências (Apenas para fazer o build)
    # Você PRECISA instalar o ncc e as dependências para o build funcionar
    - name: Install Dependencies
      run: npm install 

    # 3. Compilar o Projeto com NCC (Cria a pasta 'dist' com 1 arquivo)
    - name: Bundle with NCC
      run: npm run build # Isso executa o comando "ncc build index.js -o dist"

      
       # 4. Deploy via FTP - MUITO MAIS RÁPIDO
    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }}         
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        # Agora, enviamos APENAS a pasta de build!
        localDir: "dist" 
        # ATENÇÃO: Verifique qual é o diretório de destino no seu servidor Locaweb!
        remoteDir: "/public_html"
